### ISSUE TITLE
Tests automation

### ISSUE THREAD

**Issue by nolar** [zalando-incubator/kopf#13]
The project is now in the proof-of-concept stage, and lacks the tests (beside the examples, manually executed during the development).

It needs some good unit tests to freeze its current state, so that we could continue to add new features safely.

Separate the tests into the internal tests and the external promises of the interface.

Add the coverage measurements.

---

An estimation of topics to cover with the tests:

* [x] Library's public interfaces (what is exported via the main module).
* [x] #28 Object hierarchies and name/namespace/label parent-to-child propagation.
* [x] #29 Registries and `kopf.on` decorators.
* [ ] #91 (+#82) Last-seen state manipulation.
* [x] #40 Diff calculation.
* [x] #34 Handler function invocation.
* [x] #63 Event-loop running, task spawning.
* [x] #63 Watching & queueing & per-object queues/workers.
* [x] #82 Handling: cause detection and proper reaction.
* [ ] #90 (+#82) Handling: finalizers adding/removing.
* [x] #61 Handling: handler progress storage.
* [x] #35 Handling: lifecycles and handler selection.
* [ ] Sub-handler invocation and context-vars setting.
* [ ] Peering and neighbourhood awareness.
* [x] #39 CLI module loading/importing.
* [x] #39 CLI commands and options, including cluster authentication.
* [x] #71 Mocked K8s client or API calls.
* [x] #53 #54 Real-cluster execution and smoke tests.
* [x] ~#72 Coverage~ MOVED TO #99

**Comment by nolar** [comment]
The remaining parts are implemented in https://github.com/nolar/kopf/pull/519.
